expression      =   assignment
                ;

assignment      =   (call | IDENTIFIER) assign expression
                |   logicOr 
                ;

assign          =   "=" | ":=" | "+=" | "-=" | "*=" | "/=" | "%="
                ;

logicOr         =   logicAnd ("or" logicAnd)* 
                ;

logicAnd        =   equality ("and" equality)* 
                ;

equality        =   comparison (("!=" | "==") comparison)* 
                ;

comparison      =   term ((">" | ">=" | "<" | "<=") term)* 
                ;

term            =   factor (( "-" | "+" ) factor)* 
                ;

factor          =   unary (( "*" | "/" | "%" ) unary)* 
                ;

unary           =   ("!" | "-") unary | call 
                ;

call            =   primary ("(" arguments ? ")" | "." IDENTIFIER | "[" expression "]")* 
                ;

primary         =   "true" | "false" | "null" | "this" 
                |   NUMBER | STRING | IDENTIFIER 
                |   "(" expression ")" 
                |   function
                |   arrowFunction
                ;

function        =   "func" (lambda | arrowFunction) 
                ;

arrowFunction   =   "(" parameters? ")" "=>" expression
                ;

lambda          =   "(" parameters? ")" block
                ;
