declaration =   funcDecl
            |   statement
            ;

funcDecl    =   "func" IDENTIFIER lambda "
            ;
        
statement   =   exprStmt
            |   ifStmt
            |   whileStmt
            |   printStmt
            |   returnStmt
            |   forStmt
            |   block
            ;

exprStmt    =   expression ";" ;

ifStmt      =   "if" "(" expression ")" statement ("else" statement)? 
            ;

whileStmt   =   "while" "(" expression ")" statement 
            ;

printStmt   =   "print" statement 
            ;

returnStmt  =   "return" statement ;

forStmt     =   "for" "(" (exprStmt | ";") expression? ";" expression? ")" statement 
            ;

block       =   "{" declaration* "}" 
            ;
