parameter       ::= IDENTIFIER (":" type)? ;

parameters      ::= parameter ("," parameter)* ;

arguments       ::= expression ("," expression)* ;

typeItems       ::= typeItem ("," typeItem)* ;

typeItem        ::= IDENTIFIER ":" type
